### ISSUE TITLE
Implement unit and integration tests for UWG_Python

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/urbanWeatherGen#10]
After a discussion with Mostapha, I'm going to swap out the temporary testing framework I wrote up with proper unit/integration tests with the pytest.py library. The new testing framework will look like the [honeybee[+] tests](https://github.com/ladybug-tools/honeybee/tree/0fc52afd4b86905f24078113296aec352c5fd63c/tests
).

TO DO:

- [x] Make tests directory in UWG dir.
- [x] Swap test.py for pytest.py
- [x] Move test_uwg.py to UWG/test dir
- [x] Sign up for travis ci.
- [x] Test out test build during github push with travis ci
- [ ] Externalize tests from readDOE.py to own test file
- [ ] delete test.py 
- [x] Add parallel dir for tests and move all test_*.py files there

**Comment by saeranv** [comment]
@chriswmackey 

So I've gotten pytest integrated with some some initial unit tests and it's working pretty smoothly:

![image](https://user-images.githubusercontent.com/1685956/30093619-8a82cd4c-9294-11e7-95bb-b73023eee4d7.png)

The next step is to integrate it with [Travis CI](https://travis-ci.org/) so that we can trigger the unit tests every time one of us pushes a commit to git.  

It looks like only a repo administrator can enable the Travis CI hook, so do you thing you can log into [travis](https://travis-ci.org/getting_started) and enable the UWG_Python repo? I should be able to enable everything else from there.

**Comment by chriswmackey** [comment]
@saeranv ,
I'll try to enable Travis CI soon after I get home.  This has also gotten me thinking that we should eventually move this repo under the Ladybug Tools organization so that it is not under my username. You should definitely get admin privileges for this repo and I'll see if I can do this as soon as I get home. If not, you will definitely get admin rights once it's under Ladybug Tools.
-Chris

**Comment by chriswmackey** [comment]
@saeranv ,
I believe that I have enabled the Travis CI hook and let me know when you get the chance to test it out.
I also confirmed that I will not be able to give you admin privileges until we move the repo under the Ladybug Tools organization so I will look into this more and will figure out a good time to do this.
-Chris

**Comment by saeranv** [comment]
@chriswmackey, 

It doesn't look like I can access your personal git repo on Travis, even if I'm a collaborator, so I ended up having to fork the UWG repo so that I could run Travis from there. 

The good news is that it works!

![image](https://user-images.githubusercontent.com/1685956/30233310-bc70f434-94c2-11e7-948c-47b031bc946f.png)

So next time you push your commits to UWG, Travis should automatically run all the tests, and Travis will send you an email if your latest commit broke one of the tests. If you want to add a test, just add the prefix "test" before the .py unit test file, and it'll autodetect it. 

Unfortunately , at this point all my pytests are failing in Travis' virtual machine, even though they're passing on my local machine. So I apologize in advance for all the extraneous git commits while I try to figure out why that is happening :/

S

**Comment by chriswmackey** [comment]
@saeranv ,
Thanks for the update.  Forking the repo sounds great for now.   I should  talk with @mostaphaRoudsari about implementing Travis across the Ladybug Tools organization so that we can keep the functionality when we move it under the organization.
Keep me posted if you figure out why the Travis tests are failing.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, @saeranv is in charge for both. I already gave the permission (in sense of GitHub permissions) to @saeranv to implement Travis integration to ladybug tools organization!

PS: Thanks @saeranv.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Thanks and I'm glad to hear that you two have been coordinating.  I guess once @saeranv gets travis working well on his own fork, he can roll out a implementation for all of Ladybug Tools.
And I second the many thanks to @saeranv .  This will be very helpful moving forward!

**Comment by saeranv** [comment]
No problem @chriswmackey @mostaphaRoudsari :)

I've managed to smooth out all the issues with travis in UWG now. It was just doing it's job correctly - I had some subtle errors relating to my file paths that were working on my machine (and passing in pytest), but weren't translating to the ubuntu container that Travis uses to run pytest.  Good to have caught that early. 

You can check out the repo's current test status with this shiny new github badge I added to our [README.md](https://github.com/chriswmackey/UWG_Python/blob/master/README.md).

**Comment by chriswmackey** [comment]
@saeranv ,
Thanks for seeing this through and it looks great.  I am very excited to get this working on all of our repos at some point soon.  On a related note, let me know when you feel comfortable with me transferring this to the Ladybug Tools organization.  It shouldn't change too much and you can see some detailed info about how everything gets transferred here:
https://help.github.com/articles/about-repository-transfers/
-Chris

**Comment by saeranv** [comment]
Looks good to me @chriswmackey let's do it 👍

**Comment by mostaphaRoudsari** [comment]
Hi @saeranv and @chriswmackey,

There are a couple of changes that should be good to do before doing the transfer. Here is a short list and we can add more to it if needed or make a separate issue.

1. Make uwg a python package. You need to re-structure  the code and also rename the repo. you can call it `pyuwg` or `uwgpy` (all lower case and no _).
2. Update README.md
3. add gitignore for files that should not really be part of the github repository like .pyc files.
4. ...

**Comment by saeranv** [comment]
@mostaphaRoudsari good point. I can take care of restructuring the package. gitgnore, and take a stab at revising the README.md

@chriswmackey what do you want to rename it as?

**Comment by saeranv** [comment]
Alright guys, I just finished some UWG_Python housekeeping.

1. Major changes restructuring uwg as a python package. The tests/ and UWG/ directories are now modules. I moved the tests module to be parallel with the UWG directory (thanks @mostaphaRoudsari  for helping me this!). And finally I changed the [initialization ](https://github.com/chriswmackey/UWG_Python/blob/master/UWG/__init__.py) of UWG so that we can get much cleaner imports of our various modules (i.e. UWG.Weather rather then UWG.weather.Weather etc).
2. Updated [README](https://github.com/chriswmackey/UWG_Python/blob/master/README.md). But not by much, still needs some more writing to describe what UWG does.
3. Added .gitignore files. Added all the test caches files, and .pyc. Our repo is a lot cleaner now. 

I'll let @chriswmackey rename the module, as well as revise the README, but other then that, how's it look @mostaphaRoudsari ? Also, I've yet to start looking at what it'll take to make everything consistent with PEP8, but I'll start a new issue for that. There are some unique challenges for this repo because it's useful to keep some names/functions the same as UWG_Matlab in the short term for testing/ comparison purposes.

**Comment by chriswmackey** [comment]
@saeranv and @mostaphaRoudsari ,

Sorry for such a late response here. Thanks, @saeranv , for getting many of the changes together.
I changed the name of the repo to be more descriptive (urbanWeatherGen).  The previous name was derived from the matlab repo that Joseph has started  and I agree that we can leave this behind.  Given that the MIT professors agreed they would use the python version going forward (assuming we finish it soon), I think it's ok to leave out the py. We will just be explicit in the README.MD that it's a python application. Let me know if you agree with the name change (I am happy to change it again).

Speaking of the README, I can take a stab at it soon.
-Chris

**Comment by chriswmackey** [comment]
I fleshed out the readme.  Feel free to make or suggest any edits.

**Comment by saeranv** [comment]
This all looks good to me @chriswmackey . I think the new readme is a good overview of the project, I [added](https://github.com/chriswmackey/urbanWeatherGen/blob/master/README.md) to the description a bit to capture some of the meteorological/building systems inputs. Revise as needed!

**Comment by mostaphaRoudsari** [comment]
> I changed the name of the repo to be more descriptive (urbanWeatherGen)

@chriswmackey,

1. A good practice is to pick a all lower case name of the python package.
2. The folder name should match the name of the repository (package). It's currently urbanWeatherGen and UWG.

I personally rather a short name as this name will be used to import the library, etc.

**Comment by saeranv** [comment]
Finished integrating this with Travis-CI, and pytest.
