### ISSUE TITLE
Translate sign(1., zenith) from matlab to python.

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/urbanWeatherGen#42]
From [solarcalcs.py](https://github.com/ladybug-tools/urbanWeatherGen/blob/master/UWG/solarcalcs.py#L201-L204)

elif (abs(self.zenith) <  1e-6):
            #TODO: Need to translate sign(1.,zenith) from matlab
            raise Exception("Error at zenith calc.")
            #tanzen = sign(1.,zenith)*math.tan(1e-6);

I still need to understand and translate sign(1.,zenith) in python. Currently if this condition is met, an error is raised.

**Comment by saeranv** [comment]
From https://www.mathworks.com/help/matlab/ref/sign.html
```
Y = sign(x) returns an array Y the same size as x, where each element of Y is:

1 if the corresponding element of x is greater than 0.

0 if the corresponding element of x equals 0.

-1 if the corresponding element of x is less than 0.

x./abs(x) if x is complex.
```

**Comment by saeranv** [comment]
Hey @hansukyang,  I got one more, final code question for you. 

What is going on here with the sign function:

```
elseif (abs(zenith) <  1.E-6)
        tanzen = sign(1.,zenith)*tan(1.E-6);
```
ref link: https://github.com/hansukyang/UWG_Matlab/blob/master/SolarCalcs.m#L116

Specifically, according to Matlab's documentation, the sign function does not take two inputs: https://it.mathworks.com/help/matlab/ref/sign.html . Is this just a mistake? 

I tried to input it sign(1,num) into octave, just in case the sign() accepts overloading that is not captured in the documentation but it's giving me an error. 

Let me know if this looks right, and what we should be entering into this part of the code.

**Comment by hansukyang** [comment]
Yeah, that looks weird. I checked the code and it seems like it's from the
original part of Bruno's code, and it'd be very rarely encountered, since
this is the condition for zenith angle of near zero, which would happen
only on spring/summer equinox at the equator. So for most cases, this would
never have been encountered. The explanation for the calculated parameter
(tanzen) can be found on the original Town Energy Balance paper if you'd
like to take a look, but I think this specific part of the code is an
error, that was never encountered for the reasons explained above.

Joseph

**Comment by saeranv** [comment]
@hansukyang 

The objective of this calculation is to get the theta0 (critical canyon angle for which solar radiation reaches the road) which is expressed by this:

```theta0 = asin(min(abs( 1./tanzen)/canAspect, 1. ));```

Do you know what the "critical canyon angle" is. That's something I'm not clear on. Is it the angle between the solar rays and the road, given a certain canyon height? 

Looking at this tanzen calculation, it's basically the tan function with regard to the zenith angle, with two special cases for situation when zenith is at 90 deg (tan approaches -/+ infinity) and at 0 deg (tan approaches zero). The former and latter creates numerical issues when trying to calculate the critical canyon angle, which is why there's the addition and subtraction of a small amount (1e-6) to keep things within a reasonable range. 

As such, for the rare case that zenith ~ 0.0 is encountered, can we just set tanzen to 1e-6 if (abs(zenith) < 1.E-6)? This gives us a "Critical canyon angle" of 90 degrees.

S

**Comment by hansukyang** [comment]
The critical canyon has to do with the street canyon orientation for given
solar angle (reference: https://www.umr-cnrm.fr/IMG/pdf/masson_2000_blm.pdf)
- imagine the difference between a North-South oriented street vs.
East-West oriented on how much of the road is illuminated by the sun at a
given time.

Yes, I believe setting tanzen to 1e-6 should be fine for zenith angle close
to zero - this (critical canyon angle of 90 deg) essentially means that the
road surface will be illuminated by the sun regardless of the street
orientation if the sun is directly overhead, which makes sense.

Joseph

**Comment by hansukyang** [comment]
Yeah, that makes sense. Given the angular diameter of the sun of about 0.5
deg, I think this level of approximation is quite reasonable.

**Comment by saeranv** [comment]
Thanks guys, I've implemented the change with this PR: https://github.com/ladybug-tools/urbanWeatherGen/issues/42
