### ISSUE TITLE
Add __repr__() and ToString() methods on the UWG Object

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/urbanWeatherGen#50]
@saeranv ,
This doesn't influence the calculation but I think it will be nice to add these methods to the UWG object when we get the chance since these affect how the UWG object will be displayed in Grasshopper.  You can see in the following image that I [have added these methods for the dragonfly objects such that they display information about the object](https://github.com/chriswmackey/Dragonfly/blob/master/newPlugin/src/Dragonfly_Dragonfly.py#L1521-L1537) but the uwgObject output currently displays as a generic python object:
![image](https://user-images.githubusercontent.com/5567574/40889748-255da966-673a-11e8-9818-43d69b86febb.png)

**Comment by saeranv** [comment]
Added it with #58, prints like this:

 ![image](https://user-images.githubusercontent.com/1685956/41449614-0711171e-7030-11e8-899b-6233ca7cdb9e.png)

Let me know if you want to change anything.

**Comment by chriswmackey** [comment]
It looks great @saeranv .  Let's close out this issue.
