### ISSUE TITLE
Copy z_meso.txt into the UWG Folder

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/urbanWeatherGen#51]
@saeranv ,
In addition to the readDOE.pkl, I have realized that this z_meso.txt file is necessary to run the UWG.  I am just thinking that we should find some way to package the minimum number of things people need to run the UWG so that we don't end up creating extra unnecessary folders in the Rhino scripts directory.  Another solution might be to just make a resources subfolder within the UWG folder that contains the resources that are critical for running the engine (like the readDOE.pkl and z_meso.txt). 

Also, I should say that, right now, I'm overwriting the RESOURCE_PATH of the UWG object in GHPython in order to avoid copying the entire resource folder in the the Rhino scripts folder.  Maybe we should have the default resource path point to such a small subfolder within the UWG folder and, on the github here, we have the more detailed resource folder that we use for testing and generating the pickle files.

What are your thoughts here?

**Comment by saeranv** [comment]
I don't have any opposition to adding a smaller subfolder within the UWG folder for the readDOE.pkl and z_meso.txt. Or just moving those two files directly into the UWG directory. The directory structure is just something I inherited from the UWG_Matlab repo, so it's something we can change, there's no structural reason for it being that way. 

Having everything we need to run the engine consolidated in the UWG directory is a logical move. Then everything in the resources folder can just be the things that have to be specified when you initialize the file.

**Comment by chriswmackey** [comment]
All sounds good and feel free to set up the subfolder whenever you're ready.

**Comment by saeranv** [comment]
@chriswmackey I've added the nested folder with this PR #55 .

Let me know if you need anything else on the Dragonfly end.

**Comment by chriswmackey** [comment]
This works great @saeranv .  Thanks for doing this.  I have everything working well on the Dragonfly end with the new folder structure:
https://github.com/chriswmackey/Dragonfly/commit/4de65e2da5bb85e28b079b5e4707de3f45940bf7#diff-1c398502f6766062cf35516df227dbdbR229
