### ISSUE TITLE
Move BEM object parameter input to own method

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/urbanWeatherGen#62]
To resolve @chriswmackey's  problem here: https://github.com/chriswmackey/Dragonfly/issues/34

Moving the building loop to it's own method should solve this.

**Comment by saeranv** [comment]
@chriswmackey this #63 should allow you to modify the BEM objects seperately. 

Specifically, I think you can run the simulation in Grasshopper like this:

```
        # run main class methods
        self.read_epw()
        self.set_input()
        self.init_BEM_obj() # Comment this line out, and initialize the BEM objects in Dragonfly here.
        self.init_input_obj()
        self.hvac_autosize()
        self.simulate()
        self.write_epw()
```

**Comment by chriswmackey** [comment]
@saeranv ,

I finished updating Dragonfly to work with the new methods:
https://github.com/chriswmackey/Dragonfly/commit/86a3b22cdd0c0dd24a0c0ebc5191ae00e435a2ce

Let me know if there is anything else on your end before release.

**Comment by saeranv** [comment]
@chriswmackey nothing on my end, the only issues left in this repo are enhancements... I think we're ready for the (soft) release!

**Comment by chriswmackey** [comment]
Wonderful!!!
I'm going to draw up some release notes in a Google doc and I'll share it with you once it's drafted.
